# Generated by Django 2.2.4 on 2019-10-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190930_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ManyToManyField(null=True, to='analysis.Group'),
        ),
    ]
